client_id = ""
name = "Banner App"
application_url = "https://your-app-url.vercel.app"
embedded = true

[access_scopes]
# https://shopify.dev/docs/api/usage/access-scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://your-app-url.vercel.app/auth/callback",
  "https://your-app-url.vercel.app/auth/shopify/callback",
  "https://your-app-url.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true
